name: Generate Directory Structure

on:
  workflow_dispatch:  # Enable manual triggering

jobs:
  generate-structure:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Run directory structure script
      run: |
        cd svsk/ai  # Change to the script's directory
        python generate_structure.py
    
    - name: Upload generated log file as artifact
      uses: actions/upload-artifact@v4
      with:
        name: directory-structure
        path: svsk/ai/structure_*.log  # Updated path to match script location
